version: 2.1

orbs:
  docker: circleci/docker@1.6.0

workflows:
  sample:  # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run. 
    # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows 
    jobs:
      - build-and-test


jobs:
  build-and-test:  
    docker:
      - image: cimg/base:2021.04 # Base image should be sufficient as we are running everything inside the docker-compose images
    steps:
      # First step is always to checkout
      - checkout
      - setup_remote_docker
      - run:
          name: Setup ion_erpnext
          command: |
            docker-compose -env .circleci/env-example f .circleci/docker-compose.yml --project-name ion up -d 
            docker logs ion_site-creator_1 -f 
      - run: 
          name: Populate test data
          command: |
            docker cp .circleci/backups ion_erpnext-worker-default_1:/home/frappe/frappe-bench/sites/mysite124.localhost/private/backups
            # Data backup files can be generated in frappe using 
            # $ bench --site mysite124.localhost backup --with-files
            docker exec ion_erpnext-worker-default_1 bench restore 20210610_132701-mysite124_localhost-database.sql.gz\
                --with-public-files                                20210610_132701-mysite124_localhost-files.tar\
                --with-private-files                               20210610_132701-mysite124_localhost-private-files.tar\
                --install-app expensify_integration
      - run: 
          name: Run bench tests
          command: |
            docker exec ion_erpnext-worker-default_1 bench --site mysite124.localhost run-tests